### PR TITLE
feat(salt-desktop): demo integration of random salt project

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR is detailed demonstration of **Salt-Desktop** integration based on https://github.com/saltstack-formulas/salt-desktop/blob/master/README.rst#integration-recommendation

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
sorry wrong repo.!!!!

**Comment by eligundry** [comment]
@noelmcloughlin what are you making? I always love to see people using my code and it seems your doing something cool

**Comment by noelmcloughlin** [comment]
Hi @eligundry, sorry to disturb your project.

The context is that I use *salt/salt-bootstrap* plus custom `installer.sh` script in three projects

- opensds/opensds-installer/salt
- saltstack-formulas/salt-desktop
- my-employer/salt-desktop

The challenge is to stop reinventing the `installer` wheel but keeping salt states/pillars isolated from the `installer` logic.  In pursuit of this aim, the  *salt/salt-desktop/installer.sh* has been rewritten many times.  I developed a procedure to overlay *saltstack-formulas/salt-desktop* over my employers *my-employer/salt-desktop* and its documented in two places.

1. procedure: https://github.com/saltstack-formulas/salt-desktop#integration-recommendation
2. example: https://github.com/noelmcloughlin/salt-desktop-overlay-demo

I needed a real-life example *salt project* as guinea pig and saw yours her : https://github.com/saltstack-formulas/salt-desktop/blob/master/contrib/design_specs/RELATED.rst#related-repos .

It looked like interesting case study. 
I'm not sure it's cool or not to do this, but just an idea/prototype. 
And writing this in bash is tricky - but it's only a prototype.

thanks
Noel

**Comment by noelmcloughlin** [comment]
Please note the idea is very immature. I doubt the procedures works right now.  However in theory there is no reason why your pillar/states cannot be extended in this manner.

**Pull request closed without merging**
